# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail_id', models.EmailField(blank=True, max_length=50)),
                ('time_stamp', models.TimeField(default=datetime.datetime(2016, 4, 17, 3, 17, 32, 612940, tzinfo=utc))),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=10)),
                ('age', models.IntegerField(default=None)),
                ('colour', models.CharField(default=None, max_length=20)),
                ('favourite', models.TextField(choices=[('CA', 'casual'), ('FO', 'formal')], default='CA', max_length=25)),
                ('foot_ware', models.TextField(choices=[('SA', 'sandels'), ('SHO', 'shoes')], default='SA', max_length=25)),
            ],
        ),
    ]
