# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('mail_id', models.EmailField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=10)),
            ],
        ),
    ]
