# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mynt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='colour',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite',
            field=models.CharField(choices=[('CA', 'casual'), ('FO', 'formal')], default='CA', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='foot_ware',
            field=models.CharField(choices=[('SA', 'sandels'), ('SHO', 'shoes')], default='SA', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_stamp',
            field=models.TimeField(default=datetime.datetime(2016, 4, 17, 3, 33, 57, 110239, tzinfo=utc)),
        ),
    ]
