# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mynt', '0002_auto_20160417_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='colour',
        ),
        migrations.AlterField(
            model_name='user',
            name='time_stamp',
            field=models.TimeField(default=datetime.datetime(2016, 4, 17, 3, 35, 10, 540864, tzinfo=utc)),
        ),
    ]
